eth:
# > Docker
    # provider: ${ETH_PROVIDER}
    # address: ${ETH_ADDRESS}
    # key: ${ETH_KEY}
    # contract:
    #     address: ${ETH_CONTRACT}
# > Local
    provider: http://localhost:8545
    address: "0x145bb30acf08b12ecdcbac0615d905a219d44515"
    key: "0x104bdc341ce484b88cd498380f54dc053eec060f58b2141109cc5013c9234406"
    contract:
        address: "0x62a4B70ae0e94625dE6Dc1725AaB8262d7B8442f"