## Server Configuration ##

# > Docker
# server.port=${PORT}

# > Local
server.port=8080

# Uncomment this for extra details
# server.error.include-stacktrace=always

server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework=DEBUG
logging.level.org.hibenate.SQL=DEBUG

spring.jackson.date-format=com.digitelts.dome.trust.registry.invoker.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false


## Database Configuration ##

# > Docker
# spring.datasource.url=${DB_URL}:${DB_PORT}/${DB_NAME}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASS}
# spring.datasource.driver-class-name=${DB_DRIVER}

# > Local server
spring.datasource.url=jdbc:mariadb://localhost:3306/trusted_registries
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

# /!\ CHANGE THIS
# create-drop => Drops table when restarting
# update => Keeps table when restarting
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.globally_quoted_identifiers=true