@startuml useCaseDiagram
left to right direction
!define RECTANGLE class

actor "DOME Operator" <<Root TAO>> as  domeOperator
actor "Registrar of Registrars" <<TAO>> as registrarOfRegistrars
actor "Trusted Participant List Registrar of Registrars" as tplRegistrarOfRegistrars
actor "Trusted Access Nodes List Registrar of Registrars" as tanlRegistrarOfRegistrars
actor "Trusted Services List Registrar of Registrars" as tslRegistrarOfRegistrars
actor "Trusted Schemas List Registrar of Registrars" as tschemaslRegistrarOfRegistrars
actor "Trusted Revoked Credentials List Registrar of Registrars" as trCredentialsListRegistrarOfRegistrars
actor "Trusted Invalid Credentials List Registrar of Registrars" as tiCredentialsListRegistrarOfRegistrars

tplRegistrarOfRegistrars <|-- registrarOfRegistrars
tanlRegistrarOfRegistrars <|-- registrarOfRegistrars
tslRegistrarOfRegistrars <|-- registrarOfRegistrars
tschemaslRegistrarOfRegistrars <|-- registrarOfRegistrars
trCredentialsListRegistrarOfRegistrars <|-- registrarOfRegistrars
tiCredentialsListRegistrarOfRegistrars <|-- registrarOfRegistrars
actor "Trusted Issuer Registrar" <<TAO>> as tiRegistrar
actor "LEAR Credential Issuers Registrar" as lcilRegistrar
tiRegistrar <|-- lcilRegistrar 

actor "Registrar" as registrar 
actor "Trusted Participant List Registrar" as tplRegistrar 
actor "Trusted Access Nodes List Registrar" as tanlRegistrar 
actor "Trusted Services List Registrar" as tslRegistrar 
actor "Trusted Schemas List Registrar" as tschemaslRegistrar
actor "Trusted Revoked Credentials List Registrar" as trCredentialsListRegistrar
actor "Trusted Invalid Credentials List Registrar" as tiCredentialsListRegistrar

registrar <|-- tplRegistrar 
registrar <|-- tanlRegistrar 
registrar <|-- tslRegistrar 
registrar <|-- tschemaslRegistrar
registrar <|-- trCredentialsListRegistrar
registrar <|-- tiCredentialsListRegistrar
tplRegistrar <|-- domeOperator
tanlRegistrar <|-- domeOperator
tslRegistrar <|-- domeOperator
tschemaslRegistrar <|-- domeOperator
trCredentialsListRegistrar <|-- domeOperator
tiCredentialsListRegistrar <|-- domeOperator

actor "Trusted Issuer" as ti
actor "Trusted Issuer" as ti
actor "Trusted Issuer" as ti
actor "LEAR Credential Issuer" as learCredentialIssuer 
ti <|-- learCredentialIssuer 

registrarOfRegistrars <|-- domeOperator
registrar <|-- domeOperator
tiRegistrar <|-- domeOperator
ti <|-- domeOperator

usecase "Register specific Registrar of Registrars at TIR" as registerTAO 
usecase "Register specific Registrar of Issuers at TIR" as registerTAOIssuers
usecase "Register specific Registrar at TIR" as registerRegistrar
usecase "Register specific Issuer at TIR" as registerIssuer
usecase "Register specific Issuer at TIR" as registerIssuer

domeOperator --> registerTAO
domeOperator --> registerTAOIssuers

registrarOfRegistrars --> registerRegistrar 
tiRegistrar --> registerIssuer




usecase "Register Trusted Participant" as registerParticipant
usecase "Register Trusted Access Node Operator" as registerAccessNode
usecase "Register Trusted Service" as registerService
usecase "Register Trusted Schema" as registerSchema
usecase "Invalidate credential" as invalidateCredential 
usecase "Revoke credential" as revokeCredential

tplRegistrar --> registerParticipant
tanlRegistrar --> registerAccessNode
tslRegistrar --> registerService
tschemaslRegistrar --> registerSchema
trCredentialsListRegistrar --> revokeCredential
tiCredentialsListRegistrar --> invalidateCredential




@enduml
